version: 2.1

executors:
  default:
    docker:
      - image: circleci/node:16.11.1
    working_directory: ~/ci-coverage-notification
    environment:
      - BASH_ENV: /home/circleci/.bashrc


jobs:
  initialization:
    executor:
      name: default
    steps:
      - checkout
      - restore_cache:
          keys:
            - node_modules-{{ checksum "yarn.lock" }}
            - node_modules-
      - run: yarn --frozen-lockfile
      - save_cache:
          paths:
            - node_modules
          key: node_modules-{{ checksum "yarn.lock" }}
      - persist_to_workspace:
          root: .
          paths:
            - .

  test:
    working_directory: ~/ci-coverage-notification
    executor:
      name: default
    steps:
      - attach_workspace:
          at: .
      - run: yarn test:coverage --ci --runInBand
      - save_cache:
          paths:
            - coverage/coverage-summary.json
          key: coverage-{{ .Branch }}
      - run:
          name: Coverage Parse
          command: |
            sudo apt-get update && sudo apt-get install -y jq --no-install-recommends
            STMT=$(cat ./coverage/coverage-summary.json | jq '.total.statements.pct')
            BRANCH=$(cat ./coverage/coverage-summary.json | jq '.total.branches.pct')
            FUNCS=$(cat ./coverage/coverage-summary.json | jq '.total.functions.pct')
            LINES=$(cat ./coverage/coverage-summary.json | jq '.total.lines.pct')
            echo $STMT $BRANCH $FUNCS $LINES
      - store_artifacts:
          path: ~/ci-coverage-notification/coverage
          destination: coverage

workflows:
  version: 2
  workflow:
    jobs:
      - initialization
      - test:
          requires:
            - initialization
