version: 2.1

executors:
  default:
    docker:
      - image: circleci/node:16.11.1
    working_directory: ~/ci-coverage-notification
    environment:
      - BASH_ENV: /home/circleci/.bashrc


jobs:
  initialization:
    executor:
      name: default
    steps:
      - checkout
      - restore_cache:
          keys:
            - node_modules-{{ checksum "yarn.lock" }}
            - node_modules-
      - run: yarn --frozen-lockfile
      - save_cache:
          paths:
            - node_modules
          key: node_modules-{{ checksum "yarn.lock" }}
      - persist_to_workspace:
          root: .
          paths:
            - .

  test:
    working_directory: ~/ci-coverage-notification
    executor:
      name: default
    steps:
      - attach_workspace:
          at: .
      # mainのCoverageを復旧する
      - restore_cache:
          keys: 
            - coverage-base-
            - coverage-base
      - run: 
          name: Run Test
          command: |
            yarn test:coverage --ci --runInBand
      - run:
          name: Rename Coverage Directory By Main Branch
          command: |
            if [ ${CIRCLE_BRANCH} == "main" ]; then
              mv ./coverage ./coverage-base
            fi
      # 保存はするがmainのみを使うので実質使ってない
      - save_cache:
          paths:
            - ~/ci-coverage-notification/coverage-base
          key: coverage-base-{{ checksum "./coverage-base/coverage-summary.json" }}
      - run:
          name: Coverage Parse & Post Pull Request
          command: |
            if [ ${CIRCLE_BRANCH} == "main" ]; then
              echo NO REPORT MAIN
            else
              sudo apt-get update && sudo apt-get install -y jq --no-install-recommends
              BRANCH_NAME=$(echo ${CIRCLE_BRANCH} | sed -e "s/\//_/")
              CURRENT_JSON=$(cat ./coverage/coverage-summary.json)
              CUR_STMT=$(echo $CURRENT_JSON | jq '.total.statements.pct')
              CUR_BRANCH=$(echo $CURRENT_JSON | jq '.total.branches.pct')
              CUR_FUNCS=$(echo $CURRENT_JSON | jq '.total.functions.pct')
              CUR_LINES=$(echo $CURRENT_JSON | jq '.total.lines.pct')

              MAIN_JSON=$(cat ./coverage-base/coverage-summary.json)
              MAIN_STMT=$(echo $MAIN_JSON | jq '.total.statements.pct')
              MAIN_BRANCH=$(echo $MAIN_JSON | jq '.total.branches.pct')
              MAIN_FUNCS=$(echo $MAIN_JSON | jq '.total.functions.pct')
              MAIN_LINES=$(echo $MAIN_JSON | jq '.total.lines.pct')

              echo '=========================================================='
              echo '         | Stmts | Branch | Funcs | Lines | '
              echo '=========================================================='
              echo " main    | $MAIN_STMT | $MAIN_BRANCH | $MAIN_FUNCS | $MAIN_LINES "
              echo '=========================================================='
              echo " current | $CUR_STMT | $CUR_BRANCH | $CUR_FUNCS | $CUR_LINES "
              echo '=========================================================='
              if [ ${CI_PULL_REQUEST} ]; then
                coverage_report=echo "Hello World"
                curl -X POST \
                  -H 'Content-Type:application/json' \
                  -u ${GITHUB_USERNAME}:${GITHUB_APPS_TOKEN} \
                  -d "{\"body\":\"${coverage_report}"}" \
                  "https://api.github.com/repos/${GITHUB_USER}/${GITHUB_REPO}/issues/${CIRCLE_PULL_REQUEST##*/}/comments"
              fi
            fi
      - store_artifacts:
          path: ~/ci-coverage-notification/coverage
          destination: coverage

workflows:
  version: 2
  workflow:
    jobs:
      - initialization
      - test:
          requires:
            - initialization
