version: 2.1

executors:
  default:
    docker:
      - image: circleci/node:16.11.1
    working_directory: ~/ci-coverage-notification
    environment:
      - BASH_ENV: /home/circleci/.bashrc


jobs:
  initialization:
    executor:
      name: default
    steps:
      - checkout
      - restore_cache:
          keys:
            - node_modules-{{ checksum "yarn.lock" }}
            - node_modules-
      - run: yarn --frozen-lockfile
      - save_cache:
          paths:
            - node_modules
          key: node_modules-{{ checksum "yarn.lock" }}
      - persist_to_workspace:
          root: .
          paths:
            - .

  test:
    working_directory: ~/ci-coverage-notification
    executor:
      name: default
    steps:
      - attach_workspace:
          at: .
      - run: 
          name: Run Test
          command: |
            yarn test:coverage --ci --runInBand
      - run:
          name: Rename Coverage Summary
          command: |
            BRANCH_NAME=$(echo ${CIRCLE_BRANCH} | sed -e "s/\//_/")
            mv ./coverage/coverage-summary.json ./coverage/coverage-summary-$BRANCH_NAME.json 
      # 保存はするがmainのみを使うので実質使ってない
      - save_cache:
          paths:
            - coverage/coverage-summary-{{ .Branch }}.json
          key: coverage-{{ .Branch }}
      # mainのCoverageを復旧する
      - restore_cache:
          keys:
            - coverage-main
      - run:
          name: Coverage Parse
          command: |
            if [ ${CIRCLE_BRANCH} == "main" ]; then
              echo NO REPORT MAIN
            else
              sudo apt-get update && sudo apt-get install -y jq --no-install-recommends
              BRANCH_NAME=$(echo ${CIRCLE_BRANCH} | sed -e "s/\//_/")
              CURRENT_JSON=$(cat ./coverage/coverage-summary-$BRANCH_NAME.json)
              STMT=$($CURRENT_JSON | jq '.total.statements.pct')
              BRANCH=$($CURRENT_JSON | jq '.total.branches.pct')
              FUNCS=$($CURRENT_JSON | jq '.total.functions.pct')
              LINES=$($CURRENT_JSON | jq '.total.lines.pct')
              echo $STMT $BRANCH $FUNCS $LINES
            fi
      - store_artifacts:
          path: ~/ci-coverage-notification/coverage
          destination: coverage

workflows:
  version: 2
  workflow:
    jobs:
      - initialization
      - test:
          requires:
            - initialization
